---

- name: add certificate authority 
  win_shell: |
       Install-WindowsFeature AD-Certificate
       Install-WindowsFeature RSAT-ADCS-Mgmt
       Install-AdcsCertificationAuthority -CACommonName "ADTEST07 Root CA" -CAType EnterpriseRootCa -HashAlgorithmName SHA1 -KeyLength 2048 -ValidityPeriod Years -ValidityPeriodUnits 100 -Confirm:$false
       Install-WindowsFeature ADCS-Web-Enrollment
       Install-AdcsWebEnrollment -Confirm:$false

- name: enable network discovery
  win_shell: |
        netsh advfirewall firewall set rule group='network discovery' new enable=yes