---

- name: change administrator password
  win_shell: |
       Set-ADAccountPassword -Identity 'CN=Administrator,CN=users,DC=adtest07,DC=org' -Reset -NewPassword (ConvertTo-SecureString -AsPlainText "{{passadmin}}" -Force)
